# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-03 06:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Unibook', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='category',
            field=models.ManyToManyField(to='Unibook.Category'),
        ),
        migrations.AlterField(
            model_name='book',
            name='mobile_number',
            field=models.DecimalField(decimal_places=0, max_digits=11),
        ),
        migrations.AlterField(
            model_name='book',
            name='number',
            field=models.DecimalField(decimal_places=0, max_digits=4),
        ),
        migrations.AlterField(
            model_name='book',
            name='translater',
            field=models.CharField(blank=True, max_length=32),
        ),
    ]
